# Generated by Django 3.1.3 on 2020-11-20 13:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_pizza_size'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pizza',
            managers=[
                ('regular', django.db.models.manager.Manager()),
            ],
        ),
    ]
