# Generated by Django 3.1.3 on 2020-11-20 13:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_auto_20201120_1315'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pizza',
            managers=[
                ('Regular_pizza', django.db.models.manager.Manager()),
            ],
        ),
    ]
