# Generated by Django 3.1.3 on 2020-11-21 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_auto_20201120_1336'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pizza',
            managers=[
            ],
        ),
    ]
